# Probabilities

## Required imports

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Data sources

### Getting DataFrame

In [2]:
def get_df(file_name: str):
  filepath = Path("..")/"data"/file_name
  return pd.read_csv(filepath, index_col=0)

### Sources

In [3]:
amir_deals = get_df('amir_deals.csv')
world_happiness = get_df('world_happiness.csv')

## What is probability

(_2026-04-18T11:02:35+01:00Z - AI Generated with Gemini 3 Flash - Thinking_)

At its simplest, **probability** is the branch of mathematics that quantifies uncertainty. It measures how likely an event is to occur, represented as a value between **0** and **1** (or 0% to 100%).

## Calculating probabilities

### What's the probability of an event?

$$P(\text{event}) = \frac{\text{\# ways event can happen}}{\text{total \# of possible outcomes}}$$

## Randomness

Programming languages uses something called "pseudo-random"

### Pseudo-random

(_2026-06-30T14:02:21+07:00 - AI Generated with Gemini 3.5 Flash (Medium)_)

Pseudo-random describes a sequence of numbers or values that appears to be random but is actually generated by a deterministic mathematical formula or algorithm.

## Generating Random Values

In [4]:
# Note the code below sets the Global seed; recommend to avoid
# np.random.seed(42)

# Instead generate local random seed
rng = np.random.default_rng(seed=42)
rng.random(3)

array([0.77395605, 0.43887844, 0.85859792])

## Getting Samples

### Without replacement

In [5]:
# Including the random_state, localises the random seed
amir_deals.sample(5, random_state=42)

       product   client status   amount  num_users
20   Product I  Current    Won  3220.45         45
46   Product B  Current    Won  8614.12         17
141  Product B  Current   Lost  5856.18         45
31   Product C      New    Won  6151.14         66
68   Product B  Current    Won  4571.26         19

### With replacement

In [6]:
# Including the random_state, localises the random seed
amir_deals.sample(5, random_state=42, replace=True)

       product   client status   amount  num_users
103  Product D      New   Lost  1196.53         63
93   Product A  Current    Won  4509.96         92
15   Product B  Current   Lost  7030.54         41
107  Product H  Current    Won  4547.97         13
72   Product A  Current    Won  5945.63         55

## Independent events

Two events are **independent** if the probability of the second event **isn't** affected by the outcome of the first event.

Where **no** replacement sampling has taken place.

## Dependent events

Two events are **dependent** if the probability of the second event **is** affected by the outcome of the first event.

Where replacement sampling has taken place.

## Calculating probabilities - product types

In [7]:
# Count the deals for each product
counts = amir_deals['product'].value_counts()
counts

product
Product B    62
Product D    40
Product A    23
Product C    15
Product F    11
Product H     8
Product I     7
Product E     5
Product N     3
Product G     2
Product J     2
Name: count, dtype: int64

In [8]:
# Calculate probability of picking a deal with each product
probs = counts.apply(lambda x: x/int(counts.sum()))
probs

product
Product B    0.348315
Product D    0.224719
Product A    0.129213
Product C    0.084270
Product F    0.061798
Product H    0.044944
Product I    0.039326
Product E    0.028090
Product N    0.016854
Product G    0.011236
Product J    0.011236
Name: count, dtype: float64

Probability of selecting $Product\ C$ is $8.42%$